# general settings
name: 010z_HyCondITM_v1_f32g64s16_unpaired_gan+0id_100k_B8G1
model_type: UnpairedITMModel
scale: 1
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 10

# dataset and data loader settings
datasets:
  train:
    name: HDRTV1K_train
    type: UnpairedImageDataset
    dataroot_gt: datasets/HDRTV1K/train/train_hdr_sub
    dataroot_lq: datasets/HDRTV1K/train/train_sdr_sub
    # (for lmdb)
    # dataroot_gt: datasets/HDRTV1K/train/train_hdr_sub.lmdb
    # dataroot_lq: datasets/HDRTV1K/train/train_sdr_sub.lmdb
    filename_tmpl: '{}'
    io_backend:
      type: disk
      # (for lmdb)
      # type: lmdb

    gt_size: false
    use_hflip: false
    use_rot: false

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 4
    batch_size_per_gpu: 8
    pin_memory: true
    dataset_enlarge_ratio: 100
    prefetch_mode: ~

  val:
    name: HDRTV1K_test_lite
    type: PairedImageDataset
    dataroot_gt: datasets/HDRTV1K/test/test_lite_hdr
    dataroot_lq: datasets/HDRTV1K/test/test_lite_sdr
    io_backend:
      type: disk

# network structures
network_g:
  type: HyCondITMGenerator
  in_channels: 3
  transform_channels: 32
  global_cond_channels: 64
  spatial_cond_channels: 16

network_d:
  type: DRDiscriminator
  in_channels: 3
  n_base_features: 16

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]
  
  optim_d:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [100000]
    gamma: 0.5

  total_iter: 100000
  warmup_iter: -1  # no warm up

  # losses
  identity_opt:
    type: MSELoss
    loss_weight: !!float 0
    reduction: mean

  gan_opt:
    type: GANLoss
    gan_type: vanilla
    real_label_val: 1.0
    fake_label_val: 0.0
    loss_weight: !!float 1.0

  net_d_iters: 1
  net_d_init_iters: 0

# validation settings
val:
  val_freq: !!float 5e3
  save_img: true

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
      bit_depth: 16

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
